-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 16:21:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancoveiculos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancoveiculos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancoveiculos` DEFAULT CHARACTER SET utf8 ;
USE `bancoveiculos` ;

-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_funcionario` (
  `idtb_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(45) NOT NULL,
  `cpf_funcionario` VARCHAR(45) NOT NULL,
  `telefone_funcionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_pessoas` (
  `idpessoas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpessoas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_aluguel` (
  `idtb_aluguel` INT NOT NULL AUTO_INCREMENT,
  `data_inicial` DATE NOT NULL,
  `tb_funcionario_idtb_funcionario` INT NOT NULL,
  `tb_pessoas_idpessoas` INT NOT NULL,
  PRIMARY KEY (`idtb_aluguel`),
  INDEX `fk_tb_aluguel_tb_funcionario1_idx` (`tb_funcionario_idtb_funcionario` ASC) VISIBLE,
  INDEX `fk_tb_aluguel_tb_pessoas1_idx` (`tb_pessoas_idpessoas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_aluguel_tb_funcionario1`
    FOREIGN KEY (`tb_funcionario_idtb_funcionario`)
    REFERENCES `bancoveiculos`.`tb_funcionario` (`idtb_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluguel_tb_pessoas1`
    FOREIGN KEY (`tb_pessoas_idpessoas`)
    REFERENCES `bancoveiculos`.`tb_pessoas` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_pagamento` (
  `idtb_pagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo_pagamento` VARCHAR(45) NOT NULL,
  `preco_pagamento` VARCHAR(45) NOT NULL,
  `valor_valorkm` VARCHAR(45) NOT NULL,
  `tb_aluguel_idtb_aluguel` INT NOT NULL,
  PRIMARY KEY (`idtb_pagamento`),
  INDEX `fk_tb_pagamento_tb_aluguel1_idx` (`tb_aluguel_idtb_aluguel` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pagamento_tb_aluguel1`
    FOREIGN KEY (`tb_aluguel_idtb_aluguel`)
    REFERENCES `bancoveiculos`.`tb_aluguel` (`idtb_aluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_veiculo` (
  `idtb_veiculo` INT NOT NULL AUTO_INCREMENT,
  `marca_veiculo` VARCHAR(45) NOT NULL,
  `placa_veiculo` VARCHAR(45) NOT NULL,
  `modelo_veiculo` VARCHAR(45) NOT NULL,
  `numero_chaci_veiculo` VARCHAR(45) NOT NULL,
  `tipo_veiculo` VARCHAR(45) NOT NULL,
  `cor_veiculo` VARCHAR(45) NOT NULL,
  `capacidade_veiculo` VARCHAR(45) NOT NULL,
  `porta_mala_veiculo` VARCHAR(45) NOT NULL,
  `alugado_veiculo` CHAR(1) NOT NULL,
  `km_atual` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_pessoa_juridica` (
  `idpessoa juridica` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NOT NULL,
  `tb_pessoas_idpessoas` INT NOT NULL,
  PRIMARY KEY (`idpessoa juridica`),
  INDEX `fk_tb_pessoa_juridica_tb_pessoas1_idx` (`tb_pessoas_idpessoas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pessoa_juridica_tb_pessoas1`
    FOREIGN KEY (`tb_pessoas_idpessoas`)
    REFERENCES `bancoveiculos`.`tb_pessoas` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_pessoa_fisica` (
  `idpessoa fisica` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `cnh` VARCHAR(45) NOT NULL,
  `tb_pessoas_idpessoas` INT NOT NULL,
  PRIMARY KEY (`idpessoa fisica`),
  INDEX `fk_tb_pessoa_fisica_tb_pessoas1_idx` (`tb_pessoas_idpessoas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pessoa_fisica_tb_pessoas1`
    FOREIGN KEY (`tb_pessoas_idpessoas`)
    REFERENCES `bancoveiculos`.`tb_pessoas` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_aluguel_has_tb_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_aluguel_has_tb_veiculo` (
  `tb_aluguel_idtb_aluguel` INT NOT NULL,
  `tb_veiculo_idtb_veiculo` INT NOT NULL,
  `kmfinal` VARCHAR(45) NOT NULL,
  `kminicial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tb_veiculo_idtb_veiculo`),
  INDEX `fk_tb_aluguel_has_tb_veiculo_tb_veiculo1_idx` (`tb_veiculo_idtb_veiculo` ASC) VISIBLE,
  INDEX `fk_tb_aluguel_has_tb_veiculo_tb_aluguel1_idx` (`tb_aluguel_idtb_aluguel` ASC) VISIBLE,
  CONSTRAINT `fk_tb_aluguel_has_tb_veiculo_tb_aluguel1`
    FOREIGN KEY (`tb_aluguel_idtb_aluguel`)
    REFERENCES `bancoveiculos`.`tb_aluguel` (`idtb_aluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluguel_has_tb_veiculo_tb_veiculo1`
    FOREIGN KEY (`tb_veiculo_idtb_veiculo`)
    REFERENCES `bancoveiculos`.`tb_veiculo` (`idtb_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





INSERT INTO `tb_funcionario` (nome_funcionario, cpf_funcionario, telefone_funcionario) VALUES
('João Silva', '11122233344', '(62) 91234-5678'),
('Maria Souza', '22233344455', '(62) 92345-6789'),
('Pedro Costa', '33344455566', '(62) 93456-7890'),
('Ana Lima', '44455566677', '(62) 94567-8901'),
('Carlos Santos', '55566677788', '(62) 95678-9012'),
('Beatriz Carvalho', '66677788899', '(62) 96789-0123'),
('Fernando Torres', '77788899900', '(62) 97890-1234'),
('Juliana Pereira', '88899900011', '(62) 98901-2345'),
('Bruno Rocha', '99900011122', '(62) 99012-3456'),
('Isabela Mendes', '00011122233', '(62) 90123-4567'),
('Marcos Dias', '11122233344', '(62) 91234-5678'),
('Laura Costa', '22233344455', '(62) 92345-6789'),
('Lucas Nunes', '33344455566', '(62) 93456-7890'),
('Renata Oliveira', '44455566677', '(62) 94567-8901'),
('Thiago Moreira', '55566677788', '(62) 95678-9012'),
('Paula Gomes', '66677788899', '(62) 96789-0123'),
('Gabriel Freitas', '77788899900', '(62) 97890-1234'),
('Camila Souza', '88899900011', '(62) 98901-2345'),
('Ricardo Martins', '99900011122', '(62) 99012-3456'),
('Fernanda Lima', '00011122233', '(62) 90123-4567');

INSERT INTO `tb_pessoas` (nome, tipo, telefone) VALUES
('João Silva', 'pf', '(62) 91234-5678'),
('Maria Souza', 'pf', '(62) 92345-6789'),
('Empresa X', 'pj', '(62) 93456-7890'),
('Pedro Costa', 'pf', '(62) 94567-8901'),
('Ana Lima', 'pf', '(62) 95678-9012'),
('Empresa Y', 'pj', '(62) 96789-0123'),
('Beatriz Carvalho', 'pf', '(62) 97890-1234'),
('Fernando Torres', 'pf', '(62) 98901-2345'),
('Juliana Pereira', 'pf', '(62) 99012-3456'),
('Empresa Z', 'pj', '(62) 90123-4567'),
('Bruno Rocha', 'pf', '(62) 91234-5678'),
('Isabela Mendes', 'pf', '(62) 92345-6789'),
('Marcos Dias', 'pf', '(62) 93456-7890'),
('Laura Costa', 'pf', '(62) 94567-8901'),
('Lucas Nunes', 'pf', '(62) 95678-9012'),
('Renata Oliveira', 'pf', '(62) 96789-0123'),
('Thiago Moreira', 'pf', '(62) 97890-1234'),
('Empresa A', 'pj', '(62) 98901-2345'),
('Paula Gomes', 'pf', '(62) 99012-3456'),
('Gabriel Freitas', 'pf', '(62) 90123-4567');

INSERT INTO `tb_veiculo` (marca_veiculo, placa_veiculo, modelo_veiculo, numero_chaci_veiculo, tipo_veiculo, cor_veiculo, capacidade_veiculo, porta_mala_veiculo, alugado_veiculo, km_atual) VALUES
('Toyota', 'ABC1234', 'Corolla', '1HGBH41JXMN109186', 'Sedan', 'Preto', '5', '500L', 'N', '10'),
('Honda', 'DEF5678', 'Civic', '1HGBH41JXMN109187', 'Sedan', 'Branco', '5', '520L', 'S', '23'),
('Ford', 'GHI9012', 'Focus', '1HGBH41JXMN109188', 'Hatch', 'Azul', '5', '450L', 'N', '34'),
('Chevrolet', 'JKL3456', 'Onix', '1HGBH41JXMN109189', 'Hatch', 'Vermelho', '5', '400L', 'N', '54'),
('Fiat', 'MNO7890', 'Argo', '1HGBH41JXMN109190', 'Hatch', 'Cinza', '5', '370L', 'S', '65'),
('Volkswagen', 'PQR1234', 'Golf', '1HGBH41JXMN109191', 'Hatch', 'Preto', '5', '460L', 'N', '67'),
('Hyundai', 'STU5678', 'HB20', '1HGBH41JXMN109192', 'Hatch', 'Branco', '5', '420L', 'S', '43'),
('Nissan', 'VWX9012', 'Kicks', '1HGBH41JXMN109193', 'SUV', 'Azul', '5', '500L', 'N', '23'),
('Jeep', 'YZA3456', 'Renegade', '1HGBH41JXMN109194', 'SUV', 'Vermelho', '5', '520L', 'S', '43'),
('Renault', 'BCD7890', 'Captur', '1HGBH41JXMN109195', 'SUV', 'Cinza', '5', '480L', 'N', '54');

INSERT INTO `tb_pessoa_juridica` (cnpj, tb_pessoas_idpessoas) VALUES
('12.345.678/0001-00', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Empresa X')),
('23.456.789/0001-11', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Empresa Y')),
('34.567.890/0001-22', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Empresa Z')),
('45.678.901/0001-33', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Empresa A'));


INSERT INTO `tb_pessoa_fisica` (cpf, cnh, tb_pessoas_idpessoas) VALUES
('123.456.789-00', '123456789012345', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'João Silva')),
('234.567.890-11', '234567890123456', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Maria Souza')),
('345.678.901-22', '345678901234567', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Pedro Costa')),
('456.789.012-33', '456789012345678', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Ana Lima')),
('567.890.123-44', '567890123456789', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Beatriz Carvalho')),
('678.901.234-55', '678901234567890', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Fernando Torres')),
('789.012.345-66', '789012345678901', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Juliana Pereira')),
('890.123.456-77', '890123456789012', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Bruno Rocha')),
('901.234.567-88', '901234567890123', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Isabela Mendes')),
('012.345.678-99', '012345678901234', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Marcos Dias')),
('123.456.789-01', '123456789012345', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Laura Costa')),
('234.567.890-12', '234567890123456', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Lucas Nunes')),
('345.678.901-23', '345678901234567', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Renata Oliveira')),
('456.789.012-34', '456789012345678', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Thiago Moreira')),
('567.890.123-45', '567890123456789', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Paula Gomes')),
('678.901.234-56', '678901234567890', (SELECT idpessoas FROM tb_pessoas WHERE nome = 'Gabriel Freitas'));


INSERT INTO `tb_aluguel` (data_inicial, tb_funcionario_idtb_funcionario, tb_pessoas_idpessoas) VALUES
('2024-09-01', 1, 1),
('2024-09-02', 2, 2),
('2024-09-03', 3, 3),
('2024-09-04', 4, 4),
('2024-09-05', 5, 5),
('2024-09-06', 6, 6),
('2024-09-07', 7, 7),
('2024-09-08', 8, 8),
('2024-09-09', 9, 9),
('2024-09-10', 10, 10);



INSERT INTO `tb_pagamento` (tipo_pagamento, preco_pagamento, valor_valorkm, tb_aluguel_idtb_aluguel) VALUES
('Cartão de Crédito', '150.00', '0.50', '1'),
('Dinheiro', '100.00', '0.45', '1'),
('Transferência', '120.00', '0.48', '1'),
('Pix', '130.00', '0.47', '1'),
('Boleto', '140.00', '0.46', '1'),
('Cartão de Débito', '160.00', '0.55', '1'),
('Dinheiro', '110.00', '0.49', '1'),
('Pix', '125.00', '0.51', '1'),
('Cartão de Crédito', '180.00', '0.60', '1'),
('Transferência', '140.00', '0.52', '1'),
('Boleto', '135.00', '0.53', '1'),
('Cartão de Débito', '150.00', '0.58', '1'),
('Dinheiro', '90.00', '0.43', '1'),
('Transferência', '170.00', '0.54', '1'),
('Pix', '160.00', '0.57', '1'),
('Boleto', '145.00', '0.59', '1'),
('Dinheiro', '105.00', '0.48', '1'),
('Cartão de Crédito', '190.00', '0.62', '1'),
('Transferência', '200.00', '0.65', '1'),
('Pix', '175.00', '0.61', '1');

INSERT INTO `tb_aluguel_has_tb_veiculo` (tb_aluguel_idtb_aluguel, tb_veiculo_idtb_veiculo, kmfinal, kminicial) VALUES
(1, 1, '1000', '500'),
(2, 2, '2000', '1500'),
(3, 3, '3000', '2500'),
(4, 4, '4000', '3500'),
(5, 5, '5000', '4500'),
(6, 6, '6000', '5500'),
(7, 7, '7000', '6500'),
(8, 8, '8000', '7500'),
(9, 9, '9000', '8500'),
(10, 10, '10000', '9500');

