-- MySQL Script generated by MySQL Workbench
-- Thu Aug  8 15:56:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancoveiculos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancoveiculos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancoveiculos` DEFAULT CHARACTER SET utf8 ;
USE `bancoveiculos` ;

-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_pagamento` (
  `idtb_pagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo_pagamento` VARCHAR(45) NOT NULL,
  `preco_pagamento` VARCHAR(45) NOT NULL,
  `km_final` VARCHAR(45) NOT NULL,
  `valor_valorkm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_funcionario` (
  `idtb_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(45) NOT NULL,
  `cpf_funcionario` VARCHAR(45) NOT NULL,
  `telefone_funcionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_pessoas` (
  `idpessoas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpessoas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_aluguel` (
  `idtb_aluguel` INT NOT NULL AUTO_INCREMENT,
  `data_inicial` DATE NOT NULL,
  `tb_funcionario_idtb_funcionario` INT NOT NULL,
  `tb_pagamento_idtb_pagamento` INT NOT NULL,
  `tb_pessoas_idpessoas` INT NOT NULL,
  PRIMARY KEY (`idtb_aluguel`),
  INDEX `fk_tb_aluguel_tb_funcionario1_idx` (`tb_funcionario_idtb_funcionario` ASC) VISIBLE,
  INDEX `fk_tb_aluguel_tb_pagamento1_idx` (`tb_pagamento_idtb_pagamento` ASC) VISIBLE,
  INDEX `fk_tb_aluguel_tb_pessoas1_idx` (`tb_pessoas_idpessoas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_aluguel_tb_funcionario1`
    FOREIGN KEY (`tb_funcionario_idtb_funcionario`)
    REFERENCES `bancoveiculos`.`tb_funcionario` (`idtb_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluguel_tb_pagamento1`
    FOREIGN KEY (`tb_pagamento_idtb_pagamento`)
    REFERENCES `bancoveiculos`.`tb_pagamento` (`idtb_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluguel_tb_pessoas1`
    FOREIGN KEY (`tb_pessoas_idpessoas`)
    REFERENCES `bancoveiculos`.`tb_pessoas` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_veiculo` (
  `idtb_veiculo` INT NOT NULL AUTO_INCREMENT,
  `marca_veiculo` VARCHAR(45) NOT NULL,
  `placa_veiculo` VARCHAR(45) NOT NULL,
  `modelo_veiculo` VARCHAR(45) NOT NULL,
  `numero_chaci_veiculo` VARCHAR(45) NOT NULL,
  `tipo_veiculo` VARCHAR(45) NOT NULL,
  `cor_veiculo` VARCHAR(45) NOT NULL,
  `capacidade_veiculo` VARCHAR(45) NOT NULL,
  `porta_mala_veiculo` VARCHAR(45) NOT NULL,
  `alugado_veiculo` CHAR(1) NOT NULL,
  `km_inicial_veiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_pessoa_juridica` (
  `idpessoa juridica` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NOT NULL,
  `tb_pessoas_idpessoas` INT NOT NULL,
  PRIMARY KEY (`idpessoa juridica`),
  INDEX `fk_tb_pessoa_juridica_tb_pessoas1_idx` (`tb_pessoas_idpessoas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pessoa_juridica_tb_pessoas1`
    FOREIGN KEY (`tb_pessoas_idpessoas`)
    REFERENCES `bancoveiculos`.`tb_pessoas` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_pessoa_fisica` (
  `idpessoa fisica` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `cnh` VARCHAR(45) NOT NULL,
  `tb_pessoas_idpessoas` INT NOT NULL,
  PRIMARY KEY (`idpessoa fisica`),
  INDEX `fk_tb_pessoa_fisica_tb_pessoas1_idx` (`tb_pessoas_idpessoas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pessoa_fisica_tb_pessoas1`
    FOREIGN KEY (`tb_pessoas_idpessoas`)
    REFERENCES `bancoveiculos`.`tb_pessoas` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoveiculos`.`tb_aluguel_has_tb_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoveiculos`.`tb_aluguel_has_tb_veiculo` (
  `tb_aluguel_idtb_aluguel` INT NOT NULL,
  `tb_veiculo_idtb_veiculo` INT NOT NULL,
  PRIMARY KEY (`tb_aluguel_idtb_aluguel`, `tb_veiculo_idtb_veiculo`),
  INDEX `fk_tb_aluguel_has_tb_veiculo_tb_veiculo1_idx` (`tb_veiculo_idtb_veiculo` ASC) VISIBLE,
  INDEX `fk_tb_aluguel_has_tb_veiculo_tb_aluguel1_idx` (`tb_aluguel_idtb_aluguel` ASC) VISIBLE,
  CONSTRAINT `fk_tb_aluguel_has_tb_veiculo_tb_aluguel1`
    FOREIGN KEY (`tb_aluguel_idtb_aluguel`)
    REFERENCES `bancoveiculos`.`tb_aluguel` (`idtb_aluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluguel_has_tb_veiculo_tb_veiculo1`
    FOREIGN KEY (`tb_veiculo_idtb_veiculo`)
    REFERENCES `bancoveiculos`.`tb_veiculo` (`idtb_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- Inserts de `tb_pagamento`
INSERT INTO `bancoveiculos`.`tb_pagamento` (`tipo_pagamento`, `preco_pagamento`, `km_final`, `valor_valorkm`)
VALUES 
('Cartão', '100', '500', '0.20'),
('Dinheiro', '200', '1000', '0.30'),
('Cartão', '150', '700', '0.25'),
('Dinheiro', '250', '1200', '0.35'),
('Cartão', '180', '800', '0.22'),
('Dinheiro', '220', '1100', '0.32'),
('Cartão', '130', '600', '0.21'),
('Dinheiro', '240', '1150', '0.34'),
('Cartão', '160', '750', '0.23'),
('Dinheiro', '260', '1250', '0.36'),
('Cartão', '170', '780', '0.24'),
('Dinheiro', '270', '1300', '0.37'),
('Cartão', '140', '650', '0.20'),
('Dinheiro', '280', '1350', '0.38'),
('Cartão', '190', '820', '0.26'),
('Dinheiro', '290', '1400', '0.39'),
('Cartão', '120', '550', '0.19'),
('Dinheiro', '300', '1450', '0.40'),
('Cartão', '110', '520', '0.18'),
('Dinheiro', '310', '1500', '0.41');


-- Inserts de `tb_funcionario`
INSERT INTO `bancoveiculos`.`tb_funcionario` (`nome_funcionario`, `cpf_funcionario`, `telefone_funcionario`)
VALUES 
('João', '12345678901', '11999999999'),
('Maria', '23456789012', '11988888888'),
('Pedro', '34567890123', '11977777777'),
('Ana', '45678901234', '11966666666'),
('Carlos', '56789012345', '11955555555'),
('Paula', '67890123456', '11944444444'),
('Lucas', '78901234567', '11933333333'),
('Fernanda', '89012345678', '11922222222'),
('Marcos', '90123456789', '11911111111'),
('Juliana', '01234567890', '11900000000'),
('Rafael', '98765432109', '11899999999'),
('Camila', '87654321098', '11888888888'),
('Thiago', '76543210987', '11877777777'),
('Larissa', '65432109876', '11866666666'),
('Bruno', '54321098765', '11855555555'),
('Tatiana', '43210987654', '11844444444'),
('Gustavo', '32109876543', '11833333333'),
('Mariana', '21098765432', '11822222222'),
('Eduardo', '10987654321', '11811111111'),
('Renata', '09876543210', '11800000000');





-- Inserts de `tb_veiculo`
INSERT INTO `bancoveiculos`.`tb_veiculo` (`marca_veiculo`, `placa_veiculo`, `modelo_veiculo`, `numero_chaci_veiculo`, `tipo_veiculo`, `cor_veiculo`, `capacidade_veiculo`, `porta_mala_veiculo`, `alugado_veiculo`, `km_inicial_veiculo`)
VALUES 
('Toyota', 'ABC1234', 'Corolla', '12345678901234567', 'Sedan', 'Branco', '5', '450', 'N', '1000'),
('Honda', 'DEF5678', 'Civic', '23456789012345678', 'Sedan', 'Preto', '5', '430', 'N', '2000'),
('Ford', 'GHI9101', 'Focus', '34567890123456789', 'Hatch', 'Prata', '5', '410', 'N', '1500'),
('Chevrolet', 'JKL1123', 'Cruze', '45678901234567890', 'Sedan', 'Azul', '5', '420', 'N', '3000'),
('Hyundai', 'MNO1415', 'Elantra', '56789012345678901', 'Sedan', 'Vermelho', '5', '440', 'N', '2500'),
('Nissan', 'PQR1617', 'Sentra', '67890123456789012', 'Sedan', 'Cinza', '5', '450', 'N', '3500'),
('Volkswagen', 'STU1819', 'Jetta', '78901234567890123', 'Sedan', 'Verde', '5', '460', 'N', '4000'),
('Fiat', 'VWX2021', 'Argo', '89012345678901234', 'Hatch', 'Amarelo', '5', '400', 'N', '4500'),
('Renault', 'YZA2223', 'Logan', '90123456789012345', 'Sedan', 'Branco', '5', '470', 'N', '5000'),
('Peugeot', 'BCD2425', '208', '01234567890123456', 'Hatch', 'Preto', '5', '380', 'N', '5500'),
('Kia', 'EFG2627', 'Cerato', '12345678901234567', 'Sedan', 'Prata', '5', '490', 'N', '6000'),
('Mitsubishi', 'HIJ2829', 'Lancer', '23456789012345678', 'Sedan', 'Azul', '5', '500', 'N', '6500'),
('BMW', 'KLM3031', '320i', '34567890123456789', 'Sedan', 'Vermelho', '5', '510', 'N', '7000'),
('Audi', 'NOP3233', 'A3', '45678901234567890', 'Hatch', 'Cinza', '5', '520', 'N', '7500'),
('Mercedes', 'QRS3435', 'C200', '56789012345678901', 'Sedan', 'Verde', '5', '530', 'N', '8000'),
('Jeep', 'TUV3637', 'Renegade', '67890123456789012', 'SUV', 'Amarelo', '5', '540', 'N', '8500'),
('Volvo', 'WXY3839', 'S60', '78901234567890123', 'Sedan', 'Branco', '5', '550', 'N', '9000'),
('Subaru', 'ZAB4041', 'Impreza', '89012345678901234', 'Hatch', 'Preto', '5', '560', 'N', '9500'),
('Mazda', 'CDE4243', '3', '90123456789012345', 'Sedan', 'Prata', '5', '570', 'N', '10000'),
('Tesla', 'FGH4445', 'Model 3', '01234567890123456', 'Sedan', 'Azul', '5', '580', 'N', '10500');


-- Inserts de `tb_pessoas`
INSERT INTO `bancoveiculos`.`tb_pessoas` (`nome`, `tipo`, `telefone`)
VALUES 
('José Silva', 'F', '11987654321'),
('Mariana Souza', 'F', '11987654322'),
('Carlos Pereira', 'F', '11987654323'),
('Ana Costa', 'F', '11987654324'),
('João Santos', 'F', '11987654325'),
('Beatriz Almeida', 'F', '11987654326'),
('Ricardo Lima', 'F', '11987654327'),
('Fernanda Oliveira', 'F', '11987654328'),
('Lucas Fernandes', 'F', '11987654329'),
('Juliana Gomes', 'F', '11987654330'),
('Paulo Ribeiro', 'F', '11987654331'),
('Carla Mendes', 'F', '11987654332'),
('Gabriel Martins', 'F', '11987654333'),
('Renata Rodrigues', 'F', '11987654334'),
('Marcos Azevedo', 'F', '11987654335'),
('Camila Rocha', 'F', '11987654336'),
('Thiago Moreira', 'F', '11987654337'),
('Aline Cardoso', 'F', '11987654338'),
('Felipe Barbosa', 'F', '11987654339'),
('Patrícia Ferreira', 'F', '11987654340'),
('Empresa A', 'J', '1133334444'),
('Empresa B', 'J', '1144445555'),
('Empresa C', 'J', '1155556666'),
('Empresa D', 'J', '1166667777'),
('Empresa E', 'J', '1177778888'),
('Empresa F', 'J', '1188889999'),
('Empresa G', 'J', '1199990000'),
('Empresa H', 'J', '1100001111'),
('Empresa I', 'J', '1111112222'),
('Empresa J', 'J', '1122223333'),
('Empresa K', 'J', '1133334444'),
('Empresa L', 'J', '1144445555'),
('Empresa M', 'J', '1155556666'),
('Empresa N', 'J', '1166667777'),
('Empresa O', 'J', '1177778888'),
('Empresa P', 'J', '1188889999'),
('Empresa Q', 'J', '1199990000'),
('Empresa R', 'J', '1100001111'),
('Empresa S', 'J', '1111112222'),
('Empresa T', 'J', '1122223333');


-- Inserts de `tb_pessoa_fisica`
INSERT INTO `bancoveiculos`.`tb_pessoa_fisica` (`cpf`, `cnh`, `tb_pessoas_idpessoas`)
VALUES 
('11111111111', 'AB123456', 1),
('22222222222', 'BC234567', 2),
('33333333333', 'CD345678', 3),
('44444444444', 'DE456789', 4),
('55555555555', 'EF567890', 5),
('66666666666', 'FG678901', 6),
('77777777777', 'GH789012', 7),
('88888888888', 'HI890123', 8),
('99999999999', 'IJ901234', 9),
('00000000000', 'JK012345', 10),
('11111222222', 'KL123456', 11),
('22222333333', 'LM234567', 12),
('33333444444', 'MN345678', 13),
('44444555555', 'NO456789', 14),
('55555666666', 'OP567890', 15),
('66666777777', 'PQ678901', 16),
('77777888888', 'QR789012', 17),
('88888999999', 'RS890123', 18),
('99999000000', 'ST901234', 19),
('00000111111', 'TU012345', 20);


-- Inserts de `tb_pessoa_juridica`
INSERT INTO `bancoveiculos`.`tb_pessoa_juridica` (`cnpj`, `tb_pessoas_idpessoas`)
VALUES 
('12345678000101', 21),
('23456789000112', 22),
('34567890000123', 23),
('45678901000134', 24),
('56789012000145', 25),
('67890123000156', 26),
('78901234000167', 27),
('89012345000178', 28),
('90123456000189', 29),
('01234567000190', 30),
('11234578000201', 31),
('22345689000212', 32),
('33456790000223', 33),
('44567801000234', 34),
('55678912000245', 35),
('66789023000256', 36),
('77890134000267', 37),
('88901245000278', 38),
('99012356000289', 39),
('00123467000290', 40);

-- Inserts de `tb_aluguel`
INSERT INTO `bancoveiculos`.`tb_aluguel` (`data_inicial`, `tb_funcionario_idtb_funcionario`, `tb_pagamento_idtb_pagamento`)
VALUES 
('2024-01-01', 1, 1),
('2024-02-01', 2, 2),
('2024-03-01', 3, 3),
('2024-04-01', 4, 4),
('2024-05-01', 5, 5),
('2024-06-01', 6, 6),
('2024-07-01', 7, 7),
('2024-08-01', 8, 8),
('2024-09-01', 9, 9),
('2024-10-01', 10, 10),
('2024-11-01', 11, 11),
('2024-12-01', 12, 12),
('2025-01-01', 13, 13),
('2025-02-01', 14, 14),
('2025-03-01', 15, 15),
('2025-04-01', 16, 16),
('2025-05-01', 17, 17),
('2025-06-01', 18, 18),
('2025-07-01', 19, 19),
('2025-08-01', 20, 20);
